### ISSUE TITLE
Mod Descriptions

### ISSUE THREAD

**Issue by BCDeshiG** [JdavisBro/toychat-java-pack#3]
I have no idea what most of these mods are so it would be helpful if you linked them in the README or something.

**Comment by JdavisBro** [comment]
me m
neither

**Comment by MrOinky** [comment]
i will add some stuff soon

**Comment by MrOinky** [comment]
added everything that i can - anyone who added other mods, please try to update their descriptions too.

**Comment by HJBit** [comment]
ill link you your mom

**Comment by HJBit** [comment]
ill try to help though

**Comment by MrOinky** [comment]
finished with #4
